dataset_path: "your_dataset_path/dataset.json"
vocab_path: "path_to_save_the_pruned_vocab/pruned_vocab.txt"
vocab_threshold: 5
batch_size: 128
num_epoch: 1024
lr: 1e-4
lambda: 5
z_dim: 128
critic_iteration: 5
img_size: 224
feature_map: 8 
embedding_size: 512
n_encoder_block: 6
n_decoder_block: 6
n_head: 8
dropout: 0.1
intermediate_dim: 2048
label_embedding_size: 128
origin_mapping: "your_path_to_the_mapping_file_origin_feature/origin_mapping.json"
destination_mapping: "your_path_to_the_mapping_file_destination_feature/destination_mapping.json"
micro_category_mapping: "your_path_to_the_mapping_file_micro_category_feature/micro_category_mapping.json"
writer_real: "your_path_to_tensorboard_writer/results_expN/logs/conditional_WGAN/real"
writer_fake: "your_path_to_tensorboard_writer/results_expN/logs/conditional_WGAN/fake"
user_name: "your_name_on_GitHub"
checkpoint_path: "path_to_store_checkpoint/results_expN/checkpoint.csv"
gen_path: "path_to_store_model_weights/results_expN/weights/generator/"
gen_opt_path: "path_to_store_optimizer_state/results_expN/opt/generator/"
critic_path: "path_to_store_model_weights/results_expN/weights/critic/"
critic_opt_path: "path_to_store_optimizer_state/results_expN/opt/critic/"